-- ============================================================================
-- F1.1 — Integración Carbon → ESG Reporting Suite
-- ============================================================================
-- NO-OP: la versión Carbon original creaba un trigger handle_new_user() que
-- insertaba en organizations + profiles al registrarse. En el modelo unificado
-- ESG ese rol lo cubre el trigger handle_new_auth_user() (creado por la
-- migración ESG 010_auth_user_profile_sync y reescrito en la puente
-- 20250420120000_users_role_unify_and_bootstrap), que inserta en public.users
-- con organization_id=NULL. La asignación de organización real se delega a
-- ensureUserProfile() en apps/web/src/lib/auth/ — flujo Carbon nativo.
--
-- Esta migración se mantiene como placeholder para preservar el orden
-- cronológico del trasplante; sin contenido SQL.

-- (sin operaciones)
