-- ============================================================================
-- F1.1 — Integración Carbon → ESG Reporting Suite
-- ============================================================================
-- NO-OP: la versión Carbon original dropeaba el trigger creado por la
-- migración 20250422120000. Como esa migración es ahora también no-op (ver
-- explicación allí), no hay nada que dropear: el trigger handle_new_auth_user
-- de ESG vive en auth.users y debe permanecer.
--
-- Se mantiene como placeholder para preservar el orden cronológico del
-- trasplante.

-- (sin operaciones)
